### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by bolindong** [kimjammer/Neuro#14]
unable to locate "request"model
how to solve it?
thanks

**Comment by kimjammer** [comment]
Hi, could I have more information? Please post your error and results from `pip list` in a code block, along with your python version. The program can be pretty finicky with how you install it, so please make sure to read the Installation section and follow it carefully.

**Comment by bolindong** [comment]
hello, this is my error and pip list. Is there any wrong operation here? 


`Traceback (most recent call last):
  File "D:\AIassistant\Neuro-0.2.0\Neuro-0.2.0\main.py", line 12, in <module>
    from llmWrappers.textLLMWrapper import TextLLMWrapper
  File "D:\AIassistant\Neuro-0.2.0\Neuro-0.2.0\llmWrappers\textLLMWrapper.py", line 5, in <module>
    from llmWrappers.abstractLLMWrapper import AbstractLLMWrapper
  File "D:\AIassistant\Neuro-0.2.0\Neuro-0.2.0\llmWrappers\abstractLLMWrapper.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

`Package Version------- -------pip     24.2`

Sorry, I don't know what pip package I should install. If there is any package missing, could you show me what I need to install in all?

Thanks.

**Comment by bolindong** [comment]
By the way, My python version is Python 3.12.2

**Comment by kimjammer** [comment]
Hi, you can find detailed installation instructions here: [https://github.com/kimjammer/Neuro#this-project](https://github.com/kimjammer/Neuro#this-project)
FYI, you must be using python 3.11 for this project (because of deepspeed).
If you are fairly new to python projects, first of all, welcome! But I must warn you that this project tends to be pretty finicky to install because of all the AI-related dependencies. Check the closed issues first if you run into mysterious errors, since a solution may have already been found there. Good luck!

**Comment by bolindong** [comment]
Thank you! Bye.
