### ISSUE TITLE
whisper listening time is too short.

### ISSUE THREAD

**Issue by tigers2020** [kimjammer/Neuro#9]
ok, I might little slow talker, because English is not my first langauge,(I am slow on native Language too anyway).
whisper listening end middle of I speaking and AI interrupted.

**Comment by kimjammer** [comment]
Increase `'post_speech_silence_duration': 0.4,` this value (in seconds) in stt.py

**Comment by tigers2020** [comment]
do you have plan to apply WebUI or Gradio to set these settings easy to adjust?

**Comment by kimjammer** [comment]
These settings can't be changed while the program is running, so I have no plans of adding a separate gradio interface. I may put a handful of the important ones in a separate configuration file though. Any settings that can be changed while the program is running is a candidate to be added to neurofrontend though.

**Comment by tigers2020** [comment]
but you could change and save settings and restart api only while WebUI or Gradio sockets are still live.

**Comment by kimjammer** [comment]
The way the program is currently set up, the STT is a core part, and it can't easily be restarted independently. Of course, anything is possible with enough effort. But I don't currently think people will need to change these settings often enough for it to be worth the added complexity. If you really want it though, contributions are always welcome. I hope that explains my thought process.

**Comment by tigers2020** [comment]
STT was just one of example, there are many things could be adjust while program is running. such as mic setting or speaker, voice reference file, or change LLM models. system_prompt too.
but if you keep lazy thinking that you don't think it needed than. ok. fine.

**Comment by kimjammer** [comment]
Hi. Neuro is just a passion project of mine that I've made open source and freely available because I think Neuro Sama is really cool and everyone should be able to understand how she might work. I have been balancing working on Neuro with university and my actual job. To do that, I prioritize certain features to work on. If you felt that I was mocking your idea, I apologize - I was only trying to explain why I may or may not implement something.

But please consider that I have given you over an hour of my time for free reading issues, finding solutions, and ensuring my instructions were correct before calling me lazy.

As for other settings, like I said before, any value that can be changed while the program is running is a candidate for implementing in neurofrontend. For anything else, you are more than welcome to implement it and open a pull request. I would be more than happy to have more people contributing features and code to this project.

Thanks.

**Comment by tigers2020** [comment]
Well, I am also very fascinated with Neuro Sama, and this is the most active project I've found. So, I hope it doesn't go away easily. If my request was offensive, I apologize.
